version: "3.7"
services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app/code
      - /usr/src/app/node_modules
    environment:
      - API_URL=http://localhost:8080
      - HTTP_PORT=8080
    ports:
      - "8080:8080"
